### ISSUE TITLE
Add MonadMaybe to all partial functions

### ISSUE THREAD

**Issue by checkraiser** [ghc-proposals/ghc-proposals#151]
Could we add a `MonadMaybe` monad to all partial functions in `Prelude` and `Base` ?
for example, for `head` function:
```
head :: (MonadMaybe m) => [a] -> m a
```

**Comment by int-index** [comment]
There are two ways to make `head` total:

* shrink the domain:
  ```
  data NonEmpty a = a :| [a]

  ne_head :: NonEmpty a -> a
  ne_head (a :| _) = a
  ```

* widen the codomain:
  ```
  m_head :: [a] -> Maybe a
  m_head (x:_) = Just x
  m_head []    = Nothing
  ```

I think shrinking the domain to make functions total is preferable. We can define `m_head` via `ne_head`:

```
nonEmpty :: [a] -> Maybe (NonEmpty a)
nonEmpty [] = Nothing
nonEmpty (x:xs) = Just (x :| xs)

m_head = fmap ne_head . nonEmpty
```

At the same time, we can't express `ne_head` via `m_head` in the total subset of Haskell.

Basically, this is separation of concerns: why should `head` check for list emptiness and return `Nothing` if the check can be performed elsewhere?

In addition to that, we also get to say stuff like this:

```
  h = ne_head xs
  t = ne_tail xs
```

If we were using `m_head` and `m_tail`, then we'd have to handle the potential failure twice (as both `m_head` and `m_tail` could return `Nothing`).

`NonEmpty`, `nonEmpty`, and `ne_head` are already in `base`: https://hackage.haskell.org/package/base-4.11.1.0/docs/Data-List-NonEmpty.html#v:head

The same line of reasoning applies to other partial functions. 

Take `(/)` from `Num`, for example. We could define a wrapper:

```
newtype NonZero a = UnsafeNonZero a

nonZero :: (Num a, Eq a) => a -> Maybe (NonZero a)
nonZero a =
  if a == 0 then Nothing else Just a

class Num a where
  (/) :: a -> NonZero a -> a
```

The problem with this is that it gets unwieldy rather quickly with wrappers. A better approach is refinement types that LiquidHaskell offers: https://ucsd-progsys.github.io/liquidhaskell-blog/

**Comment by checkraiser** [comment]
Why not abstracting out failure with `MonadMaybe` ? Because with this abstraction, not only `head`, all partial functions will have the same abstraction, and it's standard abstraction in Haskell, too. Call site could still use `[]` instead of `Maybe` for partial function result, for example.

The semantics of `head` for `[]` is different from `head` for `NonEmpty List`.
`[]` supports `head` in a context of failure.

**Comment by int-index** [comment]
>  Call site could still use `[]` instead of `Maybe` for partial function result, for example.

Could you explain what you mean by that? From the name of `MonadMaybe` I assumed it would be defined like this:

```
class Monad m => MonadMaybe m where
  just :: a -> m a
  nothing :: m a
```

and its list instance would be:

```
instance MonadMaybe [] where
  just a = [a]
  nothing = []
```

but then if you use `head` with `m ~ []`, you get `head :: [a] -> [a]`, which is not partial. Instead, it would behave as `take 1`.

**Comment by checkraiser** [comment]
No, i think `head` for `[]` should behave like: `pure (take 1)` in this case.

**Comment by nomeata** [comment]
It seems that this is a library proposal, and should go through the process outlined at https://wiki.haskell.org/Library_submissions. I will close the proposal here (but feel free to discuss further if you find it useful, the issue can still be commented on).

My personal expectation is that such a proposal will not get far; there are very good reasons not to make everything polymorphic and overloaded.
