### ISSUE TITLE
Changing direction on function type.

### ISSUE THREAD

**Issue by checkraiser** [ghc-proposals/ghc-proposals#152]
I'd love to make a discussion here to know if it's compelling enough for a proposal.

If we take a function type as `f :: B <- A`, then below are advantages:

### 1. Function composition
```
f ::     B <- A
g ::     C <- B
g . f :: C <- A
```
It's natural to read and think in type.
It's easier to follow return types, because they're fixed at one level of identation.
Instead of current backward composition with `f :: A -> B`
```
f     :: A -> B
g     :: B -> C
g . f :: A -> C (why not `f . g` here ?)
```

### 2. Function application and type-level application:
If we have
```
f :: B <- A
x :: A
then
f x ~ (B <- A) A ~ B
```
So we reason about type-level application the same as term-level application.
Instead of current backward application on type:
```
f :: A -> B
x :: A
f x ~ (A -> B) A ~ B ( why not just destructing B , instead of A )
```

### 3. `do` notation

If we have
```
f :: Monad m => m a
g :: Monad m => m b <- a
then
i could use in do block as
do
  x <- f     ~ ( a <- m a )
  y <- g x   ~ b <- (m b <- a) a
  return y   ~ m b
```

### 4. `=<<` notation
If we have
```
f :: Monad m => m a
g :: Monad m => m b <- a

then

g =<< f ~ (m b <- a) (m a) ~ m b
```

So both (3) and (4) are consistent and natural to think in type, too.

### 5. Multiple arguments function application:

If we have

```
f :: A <- B <- C <- D
and 
x :: D, y :: C, z :: B
then
f x y z ~ (A <- B <- C <- D) D C B ~ A
```
It's just normal destructing a function type to get return type.

**Comment by erikd** [comment]
In my opinion, this proposal breaks *all* current Haskell code for what I can see is close to zero benefits.

I'm not in favor of it.

**Comment by checkraiser** [comment]
@erikd Ah, it's just a matter of refactoring.
Currently, i have to use `TypeOperators` with 
```
type (<-<) b a = a -> b
infixl 0 <-<
```
to get this work.
But it's clumsy to import this to all the codes, instead of make it the default.

**Comment by erikd** [comment]
This is *very* much more than "just a matter of refactoring at type level".

There are thousands of package on Hackage containing what must be millions of lines of code. They would all need to be fixed, but that ignores what is probably also 10s of millions of lines of code in Haskell code that is not on Hackage.

In addition, what you are suggesting makes zero allowance for backwards compatibility or support for multiple versions of the compiler.

Finally, you already have a option which you currently find "clumsy" and instead are proposing pushing a *huge* breaking change on everyone else. Instead, I would suggest you add `TypeOperators` to cabal file and use a custom prelude that defines your `<-<` operator and makes it available everywhere. Doing this is maybe 2 hours work for you and has close to zero impact on the rest of the community.

**Comment by checkraiser** [comment]
It's clear now, thanks @erikd .
