### ISSUE TITLE
URL links

### ISSUE THREAD

**Issue by takenobu-hs** [ghc-proposals/ghc-proposals#2]
Hi,

Thanks for great work.

Are followings correct?

(1) URL redirected now

\- Glasgow Haskell Compiler <http://ghc.haskell.org/>
\+ Glasgow Haskell Compiler <https://www.haskell.org/ghc/>

at
https://github.com/ghc-proposals/ghc-proposals/blame/master/README.rst#L11

(2) 'bgamri' -> 'ghc-proposals'

\- https://github.com/bgamari/ghc-proposals
\+ https://github.com/ghc-proposals/ghc-proposals

at
https://github.com/ghc-proposals/ghc-proposals/blame/master/README.rst#L7
https://github.com/ghc-proposals/ghc-proposals/blame/master/README.rst#L67
https://github.com/ghc-proposals/ghc-proposals/blame/master/README.rst#L72

**Comment by bgamari** [comment]
Thanks for catching these!
