### ISSUE TITLE
Proposals should contain author information and date

### ISSUE THREAD

**Issue by mpickering** [ghc-proposals/ghc-proposals#247]
The proposals metadata should contain information about the author and also the date the proposal was accepted. 

This information seems hard to work out from the rendered proposal page:

https://ghc-proposals.readthedocs.io/en/latest/proposals/0045-pointer-rep.html

and people often refer to I, which is not timeless when decoupled from author information.

**Comment by nomeata** [comment]
Yeah, I have often regretted not having put author information in originally, also when citing proposals in papers.

Indifferent about the date, but I guess it might be nice as well.

**Comment by goldfirere** [comment]
Writing and getting a proposal accepted is not substantively different than the official academic peer-review process. I'm in full support of adding this information.

**Comment by nomeata** [comment]
Any volunteers to go through the 50 existing ones and add the data? :-)

**Comment by isovector** [comment]
I volunteer!
