### ISSUE TITLE
Amending a Proposal

### ISSUE THREAD

**Issue by andrewthad** [ghc-proposals/ghc-proposals#296]
In some of the [trailing comments](https://github.com/ghc-proposals/ghc-proposals/pull/203#issuecomment-557836258) on the `PtrRep` proposal, there's a discussion going on about modifying the proposal. However, it was already accepted. What is the procedure for modifying an accepted proposal that has not yet been implemented? I suspect that opening a PR the modifies the original proposal would be most appropriate. If this is the procedure, it would be nice to mention this, even if only briefly, in the readme.

**Comment by nomeata** [comment]
Good idea. Please see https://github.com/ghc-proposals/ghc-proposals/pull/299 and comment there.

**Comment by andrewthad** [comment]
Resolved by https://github.com/ghc-proposals/ghc-proposals/pull/299
