### ISSUE TITLE
Purpose of issue tracker

### ISSUE THREAD

**Issue by andrewthad** [ghc-proposals/ghc-proposals#297]
There's nothing in the readme about the issue tracker on this repository, but what exactly is the issue tracker for. The two kinds of issues that I see are:

1. Questions about the procedure of GHC proposals
2. Incomplete proposals that attract some discussion and then linger forever

This issue falls into the first category. I propose that the readme be amended to restrict the purpose of the issue tracker to just questions about procedure. Subsequently, all proposals on the issue tracker would be closed with a request that if the author was still interested, the proposal should be reopened as a PR.

**Comment by nomeata** [comment]
This is maybe intetionally not well defined. It is also used as a general discussion ground for whatever people want. 

I don’t see an urgent need to codify anything here, and am happy for people to use it as they see fit.

**Comment by andrewthad** [comment]
Thanks. That answers my question.
