### ISSUE TITLE
sectnum wreaks havoc on rendered proposals

### ISSUE THREAD

**Issue by andrewthad** [ghc-proposals/ghc-proposals#298]
All of the accepted proposals have strange section numbers. This is entirely a cosmetic issue, but it does make the proposals look pretty bad. At some point, `sectnum` was added to all proposals, but the effect it produces is terrible. I see things like

```
210 Motivation
...
211 Proposed Change Specification
...
```

These numbers should be 1 and 2, not 210 and 211. What was the purpose of introducing `sectnum`? Can it be removed?

**Comment by nomeata** [comment]
This is for the purpose for https://ghc-proposals.readthedocs.io/en/latest/ which was an experiment that got stuck deciding its fate.

I’ll remove them until the above site becomes “official”.
