### ISSUE TITLE
ExtraCommas has the "Accepted" label but is not in the list of accepted proposals

### ISSUE THREAD

**Issue by JakobBruenker** [ghc-proposals/ghc-proposals#317]
The proposal discussion https://github.com/ghc-proposals/ghc-proposals/pull/87, while being a closed pull request, does have the "Accepted" label, but from what I can tell is nowhere to be found on https://ghc-proposals.readthedocs.io/en/latest/

**Comment by gridaphobe** [comment]
That's probably my fault. But I'm not sure how that page is generated. It doesn't even appear to be mentioned in the README.

**Comment by JakobBruenker** [comment]
I think it's not the only proposals that's affected: https://github.com/ghc-proposals/ghc-proposals/pull/175 doesn't seem to be on the list either and shares similarities in that it's a closed PR (there are other closed PRs that are on the list), it doesn't have a link at the top of the discussion to the rendered version in the master branch, and the rendered version in the PR branch 404s.

However, the last comment in that thread says "I have learned that this proposal was subsumed by #209, thus closing."

**Comment by gridaphobe** [comment]
The README only has this to say about accepted proposals:

> If we say yes: The pull request will be merged and labeled Accepted. Its meta-data will be updated to include the acceptance date. A link to the accepted proposal is added to the top of the PR discussion, together with the sentence “The proposal has been accepted; the following discussion is mostly of historic interest.”.
>
> At this point, the proposal process is technically complete. It is outside the purview of the committee to implement, oversee implementation, attract implementors, etc.
>
> The proposal authors or other implementors are encouraged to update the proposal with the implementation status (i.e. ticket URL and the first version of GHC implementing it.)

So if we can figure out how that page is generated / deployed, let's add a note about it to that section of the README. I, at least, use it as a list of instructions for merging proposals :)

**Comment by nomeata** [comment]
That page never became official. In any case it should reflect https://github.com/ghc-proposals/ghc-proposals/tree/master/proposals which is the authorative list of accepted proposals.

The Problem with `ExtraCommas` is that it got accepted by the committe, but needed fixups by the author (or the shepherd), and I think it kinda got stuck there. I’ll follow up over there.
