### ISSUE TITLE
Template suggest using BNF

### ISSUE THREAD

**Issue by phadej** [ghc-proposals/ghc-proposals#407]
> BNF grammar and semantics of any new syntactic constructs

However there is no BNF grammar for all constructs in GHC. There are alex and happy input files, which are not "BNF".

Would it be better & more explicit to ask how GHC's `alex` and `happy` files need to be changed (omitting AST construction)?

**Comment by goldfirere** [comment]
I don't want to focus too much on the meta-syntax of BNF (e.g. write `->` or `::=`?) But you're right that many constructs lack a good starting point. I will file a PR to improve this shortly.
