### ISSUE TITLE
Absurd patterns

### ISSUE THREAD

**Issue by JakobBruenker** [ghc-proposals/ghc-proposals#421]
The discussion on #302, starting here https://github.com/ghc-proposals/ghc-proposals/pull/302#issuecomment-831342880, has recently been focused on the possibility of introducing absurd patterns. In lieu of a full proposal and in an effort to have a proper place to hold that discussion, I'm creating this issue.

Using `_|_` as tentative syntax to denote an absurd pattern, the idea is that it can appear anywhere where patterns can appear, and signifies that there is no possible non-bottom value that it could match. The compiler would complain if this is not the case. For example:

```haskell
-- currently:
fromBoolVoidAndInt :: (Bool, Void) -> Int -> String
fromBoolVoidAndInt (b, v) x -> case v of {}

-- with absurd pattern:
fromBoolVoidAndInt :: (Bool, Void) -> Int -> String
fromBoolVoidAndInt (b, _|_) x
```

Since an absurd pattern can never be successfully matched, no right-hand side is needed for this equation.

There are a few open questions, though:
 - If an absurd pattern tries to match a bottom value, is the resulting bottom value the matched value or an error about a pattern match failure (a bang in front of the absurd pattern could change this)
 - How exactly should this interact with GADTs?

Feel free to make this issue obsolete by creating a proper proposal.

**Comment by JakobBruenker** [comment]
Btw, @goldfirere, in #302 you say

> If that evaluation diverges, then the pattern-match diverges for the same reason. If that evaluation does not diverge, then the pattern-match diverges with "absurd absurd pattern" or similar.

Is it possible for an evaluation to not diverge here? I would expect that in a correct implementation, the compiler doesn't let you write an absurd pattern unless the only possibility is bottom.

**Comment by cgibbard** [comment]
From https://github.com/ghc-proposals/ghc-proposals/pull/302#issuecomment-833703285
> @cgibbard Hm, it seems fine to me to simply always treat an absurd pattern as strict, and show the error message of the bottom value that was passed as argument. It seems like a simpler solution than distinguishing between these cases, and consistent with how other patterns work, where a bang doesn't change the behavior (unless its a variable or wildcard pattern).

In many cases, that's true, but if the impossible argument was constructed by an accident of recursion, then you might be turning a message with a hint about why the program failed into an infinite loop.

It's yet again a bit of a digression, but it feels as though sometimes it would be nice if GHC could, in the event of an error, collect up all the errors produced by things that it was already sufficiently obvious were going to be forced (e.g. you don't need to do any recursion to get to the point of needing to evaluate them, or they're things involved in the same pattern match), and somehow collect all the errors together, if there happened to be more than one. So in this case, it could combine the pattern match failure from the absurd pattern, and an error from the bottom argument, supposing that it evaluates to one promptly enough. It's probably quite a convoluted change to try to make for such a slight improvement though.

One approach would be for absurd patterns to compile to code that produces an error something like:

```
oops _|_
==>
oops b = error ("Absurd pattern matched in oops: " ++ seq b "")
```

So you get an error which causes another error when printed (or perhaps the infinite loop...).

This might be too cute for its own good, and would surely be frustrating to anyone who actually wanted to catch the exception though.

**Comment by goldfirere** [comment]
Given that @JakobBruenker both started this Issue and recommended that we try out Discussions, and that the second word in the OP is "discussion", I will convert this to a Discussion. Let's see what happens!
