### ISSUE TITLE
Github discussion feature

### ISSUE THREAD

**Issue by JakobBruenker** [ghc-proposals/ghc-proposals#422]
Recently, github introduced a [discussion feature](https://docs.github.com/en/discussions).

Since most of the issues opened here are discussions, maybe it would make sense to enable discussions for this repository? (It is also possible to convert existing issues into discussions.)

The main advantage they offer over issues is that they allow threaded comments.

One might even consider using discussions for the actual proposals ([that's how they do it over in F#-land](https://github.com/fsharp/fslang-design/discussions)), though since the code review feature has turned out to be quite useful for proposals, I'm less convinced that that would make sense.

**Comment by goldfirere** [comment]
Thanks for bringing this up. Sounds like a low-risk experiment to enable this. With one more concurrence from the committee, I'll enable this feature.

**Comment by nomeata** [comment]
We don’t have much discussion that isn’t tied to a PR, but we have a few issues that are actually discussions. So sure, let’s try

**Comment by goldfirere** [comment]
Done.
