### ISSUE TITLE
Explicitly declare the absence of an instance

### ISSUE THREAD

**Issue by noughtmare** [ghc-proposals/ghc-proposals#428]
## Motivation

Instances are global and should be universally agreed upon. When a consensus is reached we can implement an instance. But when we know that an instance is controversial and we know that there is no consensus, then we can't make that explicit.

## Changes

I would suggest adding a declaration to allow us to specify explicitly absent instances:

```haskell
-- |  Use 'Sum' or 'Product' instead
noinstance Semigroup Int

-- With MultiParamTypeClasses
class Void
noinstance Void
```

With GADTs you can already implement something similar:

```haskell
class Void
instance Int ~ Bool => Void

instance Void => Semigroup Int
```

But this gives terrible error messages.

## Advantages

So, there two main advantages:

1. It allows us to generate improved error messages in many situations: GHC can stop suggesting strange instances like `Num String` as in https://github.com/haskell/errors/issues/5, users can get errors when they define instances like that, and this gives an obvious place for documenting why particular instances cannot exist.
2. It makes it possible to write unsatisfiable constraints without a hacky GADTs or TypeFamilies, e.g. `Void` is the same as `Int ~ Bool`.

## Disadvantages and problems

One disadvantage is that this prevents the creation local unexported orphan instances that implement strange instances like `Num String`. Such instances are sometimes fun to play around with, but I don't think they belong in serious code, so I don't think this is a very important problem.

Perhaps a big open question still is what to do with superclasses. Can you define `noinstance (Monad f, Monad g) => Monad (Compose f g)` and what would its semantics be? I think just disallowing superclasses could be a possible approach, but maybe `noinstance Monad (Compose f g)` is not satisfactory.

I expect that there are many problems with this idea that I cannot foresee because I don't know how difficult this will be to implement in GHC, so I am opening it as an issue instead of a proper pull request.

I have also not yet thought about interaction with other extensions like `OverlappingInstances`, hopefully it can mostly have the same semantics as `instance {-# OVERLAPPING #-} Void => ...` instances.

## Alternatives

An alternative would be a pragma like `DEPRECATED` which just causes warnings instead of errors, but that could still guide some error messages. E.g.:

```haskell
{-# NOINSTANCE Semigroup Int "Use 'Sum' or 'Product' instead" #-}
```

**Comment by adamgundry** [comment]
I think this is a good idea in principle, but rather than adding new syntax, we could do this using some relatively small modifications to the existing custom type errors machinery (see https://gitlab.haskell.org/ghc/ghc/-/issues/18310 and in particular https://gitlab.haskell.org/ghc/ghc/-/issues/18310#note_295410).

**Comment by noughtmare** [comment]
Thanks for the reference to that GHC issue, that looks like it would fit my needs. And indeed defining it in syntax is probably worse than reusing the existing superclass mechanism. I will play around with @phadej's plugin sometime. I will close this for now.
