### ISSUE TITLE
Binding Guards

### ISSUE THREAD

**Issue by noughtmare** [ghc-proposals/ghc-proposals#435]
### Main Idea

While translating an imperative algorithm to Haskell I keep running into situations where guards on binding statements would be neat and it seems like a minor syntactic extension. Here's an artificial example:

```haskell
do x | 0 <= i && i < size arr <- read arr i
     | otherwise              <- pure 0
   return x
```

Which would desugar to:

```haskell
do x <- if 0 <= i && i < size arr then
          read arr i
        else if otherwise then
          pure 0
        else
          fail "binding guard failure"
   return x
```

With a prettier error message.

### Extension 1

An extension of this idea would be to allow mixing pure and impure bindings:

```haskell
do x | 0 <= i && i < size arr <- read arr i
     | otherwise              =  0
   return x
```

If we allow this then we should really also allow pure bindings without `let` in `do` blocks for consistency. We already do that in GHCi, so why not everywhere?

Edit: I guess a problem are recursive bindings. Let bindings in `do` blocks are still recursive, so this mixing would mean that even the pure bindings cannot be recursive, which is inconsistent with the other behaviour.

### Extension 2

Initially I was actually thinking it could be really useful if it allowed for conditional bindings, like so:

```haskell
do s <- initialValue
   s | someCondition <- newValue
```

This would be desugared to:

```haskell
do s <- initialValue
   s <- if someCondition then newValue else pure s
```

I think that would be very useful in some cases, but I feel like it won't always be useful, that it is too unexpected that a missing branch indicates that the old value is kept, and it only works if the variable was already bound and now shadowed.

We could make this a bit more consistent if the semantics are to always add a `| otherwise <- pure <name>` guard to all guard lists if `<name>` is already bound.

### Conclusion

All in all, I think the main idea is a minor extension which can improve readability a bit, but I don't know if it is worth it on its own. I think both extensions are interesting but also not obviously good enough to make the cut. I did want to write this down in case maybe somebody finds a way to improve it or finds a better use-case.

**Comment by tomjaguarpaw** [comment]
Is there something insufficient about [`MultiWayIf`](https://ghc.gitlab.haskell.org/ghc/doc/users_guide/exts/multiway_if.html) for this purpose? Specifically, instead of

```haskell
do x | 0 <= i && i < size arr <- read arr i
     | otherwise              <- pure 0
   return x
```

why not

```haskell
do x <- if | 0 <= i && i < size arr -> read arr i
           | otherwise              -> pure 0
   return x
```
