### ISSUE TITLE
Why template-haskell does not provide basic QuasiQuoters?

### ISSUE THREAD

**Issue by brandonchinn178** [ghc-proposals/ghc-proposals#478]
Is there a reason why `template-haskell` doesn't provide QuasiQuoters corresponding to TH quotes `[e| ... |]`, `[d| ... |]`, etc.? A lot of packages provide QuasiQuoters that could be written as "`[e| ... |]` + extra stuff"; for example, a text interpolation library could be implemented as
```hs
-- the QuasiQuoter corresponding to [e| ... |]
eQQ :: QuasiQuoter

-- Interpolate: (let x = 1 in [text|x is: #{x}|]) == "x is: 1"
text :: QuasiQuoter
text =
  eQQ
    { quoteExp =
        appE [| concat |]
        . listE
        . map
          ( \case
            Left raw -> litE $ stringL raw
            Right interpolated -> quoteExp eQQ interpolated
          )
        . parse
    }

-- Parses "x is: #{x}" into [Left "x is: ", Right "x"]
parse :: String -> [Either String String]
```
Whereas currently, it'd have to pull in `haskell-src-meta` to parse the string.

As another example, we have a use case for easily writing lists of hlists:
```hs
rows =
  eQQ
    { quoteExp = listE . map (toHList . quoteExp eQQ) . lines
    }

-- generates [1 :& "hello" :& True :& Nil, 2 :& "world" :& False :& Nil]
[rows|
  [1, "hello", True]
  [2, "world", False]
|]
```
Today, the best way to do this without `haskell-src-meta` is to do
```hs
rows = listE . map toHList

$( rows
     [ [| [1, "hello", True] |]
     , [| [2, "world", False] |]
     ]
 )
```

Related: #260

**Comment by treeowl** [comment]
This is out of scope for a GHC proposal. You can open an issue [for the core libraries committee](https://github.com/haskell/core-libraries-committee).

**Comment by brandonchinn178** [comment]
ah my bad

**Comment by phadej** [comment]
FWIW, https://github.com/haskell/core-libraries-committee/blob/main/PROPOSALS.md is only for `base` changes.

[README](https://github.com/haskell/core-libraries-committee#suggesting-changes-to-core-libraries) says

> Because the CLC owns these libraries (including `template-haskell`) but does not maintain them, if you have an improvement to suggest for a core library (including one that affects several), please start by contacting the maintainer(s) and/or main source repositories, as listed on Hackage. If the maintainer is unsure of whether to proceed, they can come to the CLC for further guidance. On the other hand, if you struggle to reach a responsive maintainer, come to the CLC directly.

**Comment by treeowl** [comment]
Oh, good point. So should this actually just be opened as a GitLab issue for GHC?

**Comment by phadej** [comment]
> Oh, good point. So should this actually just be opened as a GitLab issue for GHC?

I'd start there.
