### ISSUE TITLE
dead link: "what should a proposal look like?"

### ISSUE THREAD

**Issue by noughtmare** [ghc-proposals/ghc-proposals#481]
In the README.rst under the heading "The life cycle of a proposal"

Here in the blame: 
https://github.com/ghc-proposals/ghc-proposals/blame/50c50ee49103749537c08c0219a72ae430483b8a/README.rst#L57

The link "What should a proposal look like?" points to https://github.com/ghc-proposals/ghc-proposals#what-should-a-proposal-look-like which doesn't seem to exist.

**Comment by nomeata** [comment]
Thanks for noticing! That section was removed in 011ee5214731cf5034ce04ef305a877c54a34cb0, as it was made redundant with the templates. I’ll remove the link to that section.
