### ISSUE TITLE
Export minusNaturalMaybe from Numeric.Natural

### ISSUE THREAD

**Issue by Zemyla** [ghc-proposals/ghc-proposals#490]
It's a safe function, and is faster and more total than comparing and then subtracting. And it's already in `GHC.Natural`, so exporting it would take only one line of code.

**Comment by nomeata** [comment]
Sorry for the red tape, but I believe that this should be discussed at https://github.com/haskell/core-libraries-committee?

**Comment by sjakobi** [comment]
This proposal was discussed in https://github.com/haskell/core-libraries-committee/issues/45, accepted and implemented. So this issue can be closed now.
