### ISSUE TITLE
Where to put implementation details in a proposal?

### ISSUE THREAD

**Issue by noughtmare** [ghc-proposals/ghc-proposals#554]
The template says this in the proposed change specification:

> Note, however, that this section should focus on a precise specification; it need not (and should not) devote space to implementation details -- there is a separate section for that.

It is not obvious to me which section this is referring to.

**Comment by simonpj** [comment]
How about "Implementation plan" of https://github.com/ghc-proposals/ghc-proposals/blob/master/proposals/0000-template.rst

**Comment by noughtmare** [comment]
Ah, now that I think about it more, that does make sense. I was thinking of different kind of implementation details, not who will implement it and what resources will be necessary.

**Comment by adamgundry** [comment]
Perhaps we should change the text in the template to make explicit that the "Implementation plan" section is intended for implementation details as well as resources?

**Comment by tomjaguarpaw** [comment]
Would you mind changing the title of this issue to

> Where to put implementation details in a proposal?

"Concerns" is ambiguous. As it is, each time I get an email about this I read it as "Where to put implementation _worries_ in a proposal?".

**Comment by noughtmare** [comment]
I thought this was just a brain fart on my part, but I guess being more explicit won't hurt. I'll make a small pull request.
