### ISSUE TITLE
Backwards compatibility

### ISSUE THREAD

**Issue by adamgundry** [ghc-proposals/ghc-proposals#578]
In the light of discussions about stability (e.g. https://discourse.haskell.org/t/language-library-and-compiler-stability-moved-from-ghc-9-6-migration-guide/5745), I think it would be a good idea if we made backwards compatibility a more explicit consideration in the proposals process.

I've tended to use the "Costs and Drawbacks" section of a proposal to discuss backwards compatibility concerns, but I realise now that the template doesn't direct authors to do that. Perhaps we should add a section to the proposal format for backwards compatibility? That would give somewhere for proposals to explain their impact on existing code and any steps to aid migration (e.g. introducing warnings before removing a feature).

I think we should also extend the review criteria to discuss backwards compatibility. @bgamari made [some good suggestions](https://discourse.haskell.org/t/language-library-and-compiler-stability-moved-from-ghc-9-6-migration-guide/5745/59):
>
> (3) I think points to an area where the GHC Proposals Process could be improved. The proposal recognizes that the change may break existing programs and says that the programs should adjust their whitespace to match the new whitespace rules. However, the proposal is silent on breakage extent, migration timeline, pre-breakage user warnings, or how tools might help aid migration. The first item is understandable as the proposal pre-dates head.hackage being an easily-used tool for characterising this sort of impact (although Ryan did [adapt](https://gitlab.haskell.org/ghc/head.hackage/-/merge_requests/62/diffs) head.hackage). However, today we could decide that the proposal process should do better in all of these areas:
>
> - we could require an approximate impact assessment for syntactic changes (e.g. how many occurrences of the affected token sequences does grep find on Hackage?)
> - alternatively, if grepping for affected syntax is too fiddly, the committee could instead require a second phase of approval such that, when an implementation is ready, a proper head.hackage study can be performed. In light of the results of this study the committee and proposal could design an appropriate migration strategy before final approval.
> - the committee could adopt a strategy similar to that of the CLC, requiring a warning period for any change that breaks user programs
> - with the continued progress of ghc-exactprint, I am hopeful that we are now in a better position to provide automated refactoring tools to facilitate mechanical migration for this sort of change. This particular change would be a great test-bed for this sort of tooling.

**Comment by simonpj** [comment]
I agree.  Having an explicit Backward Compatibility section would be an excellent prompt, especially if we add text giving examples of what to cover.

**Comment by tchoutri** [comment]
In the light of the emergency amendment and patch to #170 and its implementation, I would also suggest that proposal that were accepted without including an impact assessment section / methodology, but not yet implemented, should be re-examined.

In some cases it's fairly easy, such as using [hackage-search](https://hackage-search.serokell.io/?q=%5C%28%5C%23%5C.%5C%29) but we ought to respect the work of downstream maintainers and the disproportionate effect such proposals can have on the ecosystem.

**Comment by phadej** [comment]
> In the light of the emergency amendment and patch to https://github.com/ghc-proposals/ghc-proposals/pull/170 and its implementation, I would also suggest that the proposals that were accepted without including an impact assessment section / methodology, but not yet implemented, should be re-examined.

I don't think that case need to be blown up more that it was. The writer(s) said that the new functionality steals syntax, and that it can be fixed by adding the whitespace. They didn't think of cases where label name starts with a dot. There is a text

> This proposal steals more syntax in the same manner. E.g. the meanings of a#3, a#"foo", a#'b', and a#Foo all change.

But the `#.` case weren't mentioned. If you don't consider something, you won't be able to search for it on Hackage either.

Neither author nor committee thought about it, that's an (unfortunate) human, not a process error.

**Comment by goldfirere** [comment]
I'm in strong support of making backward compatibility a required part of both the proposal and of the evaluation process. One particular detail I'd like to bring to light is error messages: sometimes backward-incompatibility is a reasonable cost for a given proposal. (Everyone will have a different opinion about how to weigh that cost against benefits, but there is surely some cost/benefit analysis that might sometimes choose to allow some backward incompatibility.) I would like a proposal to include a sample error message that will be reported in the backward-incompatible case. That is, an incompatibility that comes with a "this changed recently; please just add `{-# I_MEAN_IT #-}` to get your code to compile" error is much more palatable (to me) than one that says "your program is borked, but I won't tell you why". Having authors imagine the error will also encourage us all to consider how to implement the error and whether doing so is feasible.

**Comment by cdornan** [comment]
+1 from me and I strongly agree with Richard's suggestion concerning the specification of failure diagnostics.

**Comment by goldfirere** [comment]
There seems to be broad consensus here that we'd like to move in this direction. @adamgundry are you happy to draft something to make a PR for this? Thanks!

**Comment by adamgundry** [comment]
@goldfirere not only am I happy to, but I already did! :grin: See #579
