### ISSUE TITLE
Dynamic programming primop

### ISSUE THREAD

**Issue by treeowl** [ghc-proposals/ghc-proposals#582]
I'm wondering if we should have

```haskell
arrayWithIndicesAndSelf# :: forall (a :: Type). Int# -> (Array# a -> Int# -> a) -> Array# a
smallArrayWithIndicesAndSelf# :: forall (a :: Type). Int# -> (SmallArray# a -> Int# -> a) -> SmallArray# a
```

The idea (assuming `Array` from `primitive`) is

```haskell
arrayWithIndicesAndSelf :: Int -> (Array a -> Int -> a) -> Array a
arrayWithIndicesAndSelf sz f = fix $ \ar ->
  arrayFromListN sz [f ar i | i <- [0..sz - 1]]
```

However, that implementation (and any using the current primops), will have to do the following:

1. Allocate an array.
2. Fill the array with bottom values.
3. Separately allocate a thunk for each element, storing a pointer to each in the array. That's not wonderful if the array is large, because the garbage collector may end up running multiple times as the thunks are allocated.

`arrayWithIndicesAndSelf#` could be implemented thus:

1. Allocate enough memory for the array and all the thunks at once. The array does not have to be filled/cleared at all.
2. Fill the array with pointers to the thunks. This will be extremely fast, because they're in a known arithmetic progression.
3. Write out the thunks. This should be quite speedy as well; they're all the same except for index.

Then

```haskell
arrayWithIndicesAndSelf :: Int -> (Array a -> Int -> a) -> Array a
arrayWithIndicesAndSelf (I# sz) f = Array $ arrayWithIndicesAndSelf# sz (\ar i -> f (Array ar) (I# i))
-- Inline this to avoid boxing in the usual case that `f` is strict in its arguments.
{-# INLINE arrayWithIndicesAndSelf #-}
```

----

The big obvious question: is it worth the trouble? Does anyone still care about this sort of lazy array programming? We don't even have a primop to `fmap` over an array yet, so maybe I'm reaching too far.

**Comment by konsumlamm** [comment]
Honestly, this seems way too specialized to warrant having a primop for it.

Taking this to the extreme:
There are lots of functions that would likely be faster with some specialized primops, why don't we also add primops for those? Heck, why do we even write Haskell in the first place, when we could do everything in C-- (or whatever primops are implemented in) and it would be faster?

**Comment by treeowl** [comment]
@konsumlamm It sure would be nice if Cmm were friendly enough and well enough known for commoners to be able to write packages using it.

**Comment by treeowl** [comment]
But yeah, I'll close this because it only allows *self* references, and not mutual references.
