### ISSUE TITLE
Or patterns: Prefix signalling or just infix?

### ISSUE THREAD

**Issue by sgraf812** [ghc-proposals/ghc-proposals#587]
Many users are quite unhappy with the syntax proposed in the currently accepted proposal #522. #585 tried to improve matters while sticking to the accepted design.

Still, users are unhappy with the prefix operator `one of` of proposal #522. During the discussion in #522, this post https://github.com/ghc-proposals/ghc-proposals/pull/522#issuecomment-1295506494 was the moment we adopted the prefix operator `one of (T1;T2)` rather than the infix operator `(T1; T2)`.

:tada: Pros for the prefix operator:

1. Easy to google: `one of Haskell` will hopefully lead to the user guide page on Or patterns. An infix operator like `(T1; T2)` would be really hard to google and might lead to confusion in e.g., code reviews (where people don't scroll up to the extension section or the extension is hidden in a cabal file). 
2. Clear signalling: `one of` means "here begins an or pattern". With infix operators, you are kind of thrown into the middle of it and have to parse the extent of the pattern.
3. Nullary Or patterns via `one of {}`, although the advantage is rather weak; perhaps it's useful for code generators

:heart: Pros for the infix operator (might be `;`, but in theory other operators such as `\/` and `|` are on the table, too):

1. Cute, less noise than `one of`.
2. Precedent: OCaml (for `|`). No other language uses a prefix operator such as `one of`.
3. If the infix operator is `;`: Harmonises well with layout in case expressions (see below). `one of` would harmonise well, too (#585), although not quite as well.

### Infix `;` and layout in `case`

Proposed by @rae in https://github.com/ghc-proposals/ghc-proposals/pull/585#issuecomment-1550485615.
We could use layout to insert `;` in `case` expressions rather nicely:

```hs
case ... of
  A -> dealWithA
  B -> dealWithB
  C
  D
  E -> dealWithTheRest
```

which is quite like

```hs
case ... of
  A -> dealWithA
  B -> dealWithB
  C; D; E -> dealWithTheRest
```

Cute. Note that neither program is currently valid Haskell (not even with `-XNondecreasingIndentation`, however that works), so there is no risk of introducing a breaking change.

Richard goes on to propose `one of { T1; T2 }` in patterns as an allowed alternative to `T1; T2` to allow for layout, e.g., 

```hs
f (one of T1
          T2) = 42
```

Not sure if that pulls its weight, though.

Note also that this layout rule might lead to confusion in conjunction with `-XLambdaCase`:

```hs
f = \cases
  []
  (x:xs) -> 42
```

Does this define a partially-defined binary function on lists or a totally-defined unary function on lists?
Fortunately, the program is currently rejected, so the latter will be the syntactically unambiguous interpretation.
It might however confuse readers, although this is arguably quite an edge case.

---

Anything else? I'm going to keep editing this post.

---

In order to gauge interest, I invite people to vote via emote to this post; :tada:  for prefix (`one of`), :heart: for infix (`;` or `|` or any other such operator).

Edit: I voted for :tada: to represent Simon's vote below

**Comment by googleson78** [comment]
Just to confirm, is :tada: the option which describes this:

Allow a multiline version without `;` by using a layouting keyword (e.g.`one of`), but also allow writing the patterns on a single line by adding `;`s between the patterns instead (basically exactly like how `do` and `let` work)

?

Additionally, in the :heart: option, is there any way to write multiline or patterns without `;`?

**Comment by nomeata** [comment]
∨! ;-) (NB: This is not a v)

**Comment by numlit2** [comment]
Does :tada: still mean `(one of {x{};y;z{}}, a)` when constructors have fields?

**Comment by hasufell** [comment]
Somehow I don't like any of the proposed solutions. Infix `;` **without** the case layout seems the lesser evil. I can see bugs slip through and confusion from the case layout.

**Comment by googleson78** [comment]
I'm sorry, but I still don't quite follow - How do you write a multiline `or` expression with no layouting herald and `;` as a separator?

I would be happy with getting pointed to a section of a proposal or a github comment as well.

**Comment by numlit2** [comment]
I'm against syntax that allows for a dense combination of two ugly and noisy symbols, namely `{{};{};{}}`.

@sgraf812 I wouldn't mind

    f (one of T1{}
              T2{}) = doSomething

It's Haskelly because we use full short english words (`one of`) and whitespace. Concise and beautiful.

But, alas, what people will do is `f (one of {T1{}; T2{}}) = 42`
And this is too much.

In comparison:
`f (one of T1{} | T2{}) = 42`

**Comment by simonpj** [comment]
>  `f (one of T1{} | T2{}) = 42`

Yes, once we give up on layout (which I advocate), and have a prefix intro (`one of`) there is a lot of flexiblity.  I quite like this one.

**Comment by phadej** [comment]
Currently `of` keyword always starts a layout rule. In fact, every keyword which starts layout always does so.

If `of` in `one of` won't start a layout, it will add quite a lot of complexity into the lexer, tying it even more to the parser.

And IMO that complexity is not worth for feature like this. (Probably lexer would need to recognise `one of` as a single lexeme).

**Comment by phadej** [comment]
Also

```haskell
case x of
  one of T1 | T2 | howToWriteGuardNow -> ...
```

**Comment by simonpj** [comment]
`oneof` is fine with me. 

Actually I don't feel very strongly about any of this.  I was just thinking that taking layout (which is not really a goal) out of the picture might simplify the discussion.

**Comment by numlit2** [comment]
> ```haskell
> case x of
>   one of T1 | T2 | howToWriteGuardNow -> ...
> ```
> 
> ?    
<br>

@phadej Why do you omit the top-level brackets? It works like this
> ```haskell
> case x of
>   (oneof T1 | T2) | someGuard -> ...
> ```

Personally I prefer the simplicity of
> ```haskell
> case x of
>   (T1 | T2) | someGuard -> ...
> ```

**Comment by tonyalaribe** [comment]
I really like the simplicity of 
```haskell
case x of
   (T1 | T2) | someGuard -> ...
```

Like in Ocalm and Rust.


This is example rust code from the rust documentation.
```rust
fn main() {
    match number {
        // Match a single value
        1 => println!("One!"),
        // Match several values
        2 | 3 | 5 | 7 | 11 => println!("This is a prime"),
        // Match an inclusive range
        13..=19 => println!("A teen"),
        _ => println!("Ain't special"),
    )
}
```

Ocaml example
```ocaml 
# let rec is_primary = function 
         | Red | Green | Blue -> true 
         | _ -> false;; 
         val is_primary : colour -> bool = <fun>
```

Barring haskell specific technical challenges, It might be beneficial to simply follow the pattern which is popular in other programming languages, since that is what most developers will try instinctively before even looking up the docs for the syntax.

**Comment by s-and-witch** [comment]
> Why do you omit the top-level brackets? It works like this
> 
> ```haskell
> case x of
>   (oneof T1 | T2) | someGuard -> ...
> ```

> I really like the simplicity of
> 
> ```haskell
> case x of
>    (T1 | T2) | someGuard -> ...
> ```

I want to notice you, that top level brackets aren't required in case patterns, so do you assume, that OR patterns MUST be enclosed into them?

**Comment by tek** [comment]
we really need a document that lays out all the possible parsing conflicts about this

**Comment by googleson78** [comment]
+1 to what @tek said. I'm no Alex+Happy guru, but this seems like it might cause potential problems. On top of that, it's very unclear to me even outside the Alex+Happy framework if some of the possibilities are actually possible without ghc having to make some "very arbitrary" decision about which parse it's going to accept

**Comment by s-and-witch** [comment]
I hope, that it should not be hard to implement what @rae proposed previously, like
```
or_pat : or_pat ';' pat
           | pat
 
 pat 
    ...
    | '(' or_pat ')'
    | one_of
    ...

one_of : one of '{' or_pat '}'
```

**Comment by chrisdone** [comment]
Voted for prefix.

Thoughts on naming: if it’s “one of” then perhaps the extension should be called OneOfPatterns. Otherwise, why not `(or X Y ..)`. Perhaps because it’s not grammatical.

Second thought: InPatterns — `f (in X Y Z) = ...` reads grammatically to me (“... is in set ...”) and is shorter and presumably doesn’t conflict with anything. I don’t think commas are needed, but that’s the lisper talking.

**Comment by sgraf812** [comment]
Hello,

I hereby declare "infix operators" the winner of the vote.

The next vote happens over in #598. It is meant to settle the choice of infix operator.

Happy voting!

**Comment by simonpj** [comment]
It seems to me that `|` is infeasible because of guards
```
case x of
   B | C | y>0 -> blah      -- No thank you!
   (B | C) | y>0 -> blah   -- Still dire
```
Semicolons would, I think, be better than this.  

I don't expect or-patterns to be common, so I still think that a prefix herald would be better still.  More explicit, less room for confusion, more greppable for.

But mostly I think that the syntactic pain is not worth the gain.  I seldom need or-patterns and when I do a let-binding sufices.
