### ISSUE TITLE
Or patterns syntax: `(p1|p2)` or `(p1;p2)`?

### ISSUE THREAD

**Issue by sgraf812** [ghc-proposals/ghc-proposals#598]
In the previous [vote on Or pattern syntax](https://github.com/ghc-proposals/ghc-proposals/issues/587), infix operator syntax won by a large margin.

In this vote, we want to settle if we rather want `(p1|p2)`, `(p1; p2)` or something entirely different, such as `(p1 \/ p2)` (or `;;`).
Note that all operators will need mandatory parentheses around them to avoid ambiguities.

**As in #587, you can vote by reacting to this post via emoji in one (or two, if you want to express dissent for one of the options) of three ways**:

Vote :tada: for `(p1|p2)`. Pros:

- Familiarity/trodden path: This is the operator that OCaml uses for Or patterns.
- Compared to `(p1;p2)`: No risk of confusion with record field matches `(T1{x=_;y=_}; T2{})`

Vote :heart: for `(p1; p2)`. Pros:

- Asymmetry expresses left bias of first match semantics well
- Compared to `(p1|p2)`: Does not steal syntax from a potential "guards-in-patterns" extension as sketched out [here](https://gitlab.haskell.org/ghc/ghc/-/wikis/view-patterns-alternative). That proposal might be a viable alternative to view pattern syntax, which [is incompatible with type-kinded patterns `f (a -> b)`](https://github.com/ghc-proposals/ghc-proposals/issues/598#issuecomment-1600648262) in a future Dependent Haskell, according to @int-index.
- Could harmonise well with layout in case expressions (see below), if we want that, in which case the outer parens could be omitted. Whether or not we want that would be another vote.

Vote :rocket: for some other operator, such as `(p1 \/ p2)`/`(p1 ' p2)`/you name it. (If this wins, we'll have another vote.)

---

### Infix `;` and layout in `case`

Proposed by @rae in https://github.com/ghc-proposals/ghc-proposals/pull/585#issuecomment-1550485615.
We could use layout to insert `;` in `case` expressions rather nicely:

```hs
case ... of
  A -> dealWithA
  B -> dealWithB
  C
  D
  E -> dealWithTheRest
```

which is quite like

```hs
case ... of
  A -> dealWithA
  B -> dealWithB
  C; D; E -> dealWithTheRest
```

Cute. Note that neither program is currently valid Haskell (not even with `-XNondecreasingIndentation`, however that works), so there is no risk of introducing a breaking change.

---

Anything else? I'm going to keep editing this post.

**Comment by JakobBruenker** [comment]
I like the layout possibility that `;` presents, but would prefer `|` if we don't allow layout.

It seems worth noting that `||` is not symmetrical (`True || undefined` is not the same as `undefined || True`), so `|` also not quite being symmetrical has some... meta-symmetry

**Comment by mixphix** [comment]
Could we use a single `'` character? AFAIK they're only used for parsing data kinds (immediately preceding a capital letter) and `Char`, where they have to be right next to non-space characters or exactly one space away from another (`' '`). What do we think of the following?
```hs
case ... of
  A -> dealWithA
  B -> dealWithB
  C ' D ' E -> dealWithTheRest

case ... of
  A -> dealWithA
  B -> dealWithB
  C
  ' D
  ' E -> dealWithTheRest
```

**Comment by tek** [comment]
Keep in mind that
```haskell
case a of
  A
  B -> ()
```
will result in two nested layouts being started at `A`. Not sure but I think this is unprecendented.

**Comment by numlit2** [comment]
> 



> Note that all operators will need mandatory parentheses around them to avoid ambiguities.

Hi @sgraf812, I like `(A{} | B)` but could you explain why parenthesis are mandatory when using `;` e.g. in

``` haskell
case x of
  A -> foo
  (B{}; C) | someGuard -> bar
```
Is `B{}; C | someGuard ->` ambiguous without parenthesis?

**Comment by lierdakil** [comment]
> Could harmonise well with layout in case expressions (see below), if we want that, in which case the outer parens could be omitted. Whether or not we want that would be another vote.

My decision here is predicated on the result of the future vote. I slightly prefer the potential flexibility of the layout rule, but if that doesn't happen, I'd rather prefer `|` on aesthetic grounds.

FTR, I'm voting :heart: for now to leave the possibility open and break the tie.

Side note, have you prototyped both of these options to make sure there will be no conflicts and no weird complications in the grammar?

**Comment by maralorn** [comment]
I really think that guards in patterns extension is beautiful and we need to be careful not to break it. Afaicr that proposal was given as the reason that ViewPatterns is not part of ghc2012.

**Comment by JakobBruenker** [comment]
@maralorn can you clarify which proposal you are referring to? I can't find one that mentions guards in patterns

**Comment by int-index** [comment]
@JakobBruenker https://ghc.haskell.org/trac/ghc/wiki/ViewPatternsAlternative

My take on this is that there are many issues with view patterns, one of them is that their syntax is the same as that of a function arrow. If we allow types in terms, then there isn't a way to tell if `f (a -> b) = ...` is a view pattern or a pattern match on the function arrow.

So I would welcome inline pattern guards as a replacement for view patterns. It would be wise to keep the `|` syntax reserved for the inline pattern guards. The currently accepted variant of the or-patterns proposal acknowledges this:
> However, | is used for guards, so it's reserved for a future [proposal](https://ghc.haskell.org/trac/ghc/wiki/ViewPatternsAlternative) that generalizes view patterns to allow guards inside patterns.

**Comment by sgraf812** [comment]
I hadn't thought about the Dependent Haskell interaction with view patterns and the resulting need for the abandoned/half-baked "guards-in-patterns" idea. A good point that I added that to the Pros of `;`.

**Comment by sgraf812** [comment]
> > 
> 
> > Note that all operators will need mandatory parentheses around them to avoid ambiguities.
> 
> Hi @sgraf812, I like `(A{} | B)` but could you explain why parentheses are mandatory when using `;` e.g. in
> 
> ```haskell
> case x of
>   A -> foo
>   (B{}; C) | someGuard -> bar
> ```
> 
> Is `B{}; C | someGuard ->` ambiguous without parentheses?

Or patterns would live at the lowest precedence level, in the `pat` non-terminal. 
Annoyingly, we get a conflict with Pattern Synonym declarations, which expect a `pat` at the end, for example `pattern P <- 42; 13` would be parsed as 2 declarations today (as if the `;` was a line separator), where the second declaration `13` has a syntax error.

I think we should change Pattern Synonym declarations so that they expect an `infixpat` (which would be a new nonterminal delgating to `infixexp`) at the end.
That's a small GHC proposal that won't cause much breakage. The only breaking change would be to declarations such as `pattern P <- 42 :: Int`, where the pattern is parsed as a pattern signature `pattern P <- (42 :: Int)`.
Apparently, no one uses that syntax: https://hackage-search.serokell.io/?q=%5Epattern%5Cb.*%3C-%5B%5E%5C%28
So it's not worth worrying.

If that proposal were accepted, we can have parens-less `;` Or patterns with the following diff:

```diff
diff --git a/compiler/GHC/Parser.y b/compiler/GHC/Parser.y
index a61a133574..3a428e5591 100644
--- a/compiler/GHC/Parser.y
+++ b/compiler/GHC/Parser.y
@@ -1632,18 +1632,18 @@ role : VARID             { sL1 $1 $ Just $ getVARID $1 }
 
 -- Glasgow extension: pattern synonyms
 pattern_synonym_decl :: { LHsDecl GhcPs }
-        : 'pattern' pattern_synonym_lhs '=' pat
+        : 'pattern' pattern_synonym_lhs '=' infixpat
          {%      let (name, args, as ) = $2 in
                  acsA (\cs -> sLL $1 (reLoc $>) . ValD noExtField $ mkPatSynBind name args $4
                                                     ImplicitBidirectional
                       (EpAnn (glR $1) (as ++ [mj AnnPattern $1, mj AnnEqual $3]) cs)) }
 
-        | 'pattern' pattern_synonym_lhs '<-' pat
+        | 'pattern' pattern_synonym_lhs '<-' infixpat
          {%    let (name, args, as) = $2 in
                acsA (\cs -> sLL $1 (reLoc $>) . ValD noExtField $ mkPatSynBind name args $4 Unidirectional
                        (EpAnn (glR $1) (as ++ [mj AnnPattern $1,mu AnnLarrow $3]) cs)) }
 
-        | 'pattern' pattern_synonym_lhs '<-' pat where_decls
+        | 'pattern' pattern_synonym_lhs '<-' infixpat where_decls
             {% do { let (name, args, as) = $2
                   ; mg <- mkPatSynMatchGroup name $5
                   ; acsA (\cs -> sLL $1 (reLoc $>) . ValD noExtField $
@@ -3327,7 +3327,11 @@ gdpat   :: { forall b. DisambECP b => PV (LGRHS GhcPs (LocatedA b)) }
 -- Bangs inside are parsed as infix operator applications, so that
 -- we parse them right when bang-patterns are off
 pat     :: { LPat GhcPs }
-pat     :  exp          {% (checkPattern <=< runPV) (unECP $1) }
+pat     : exp          {% (checkPattern <=< runPV) (unECP $1) }
+        | pat ';' exp  {% undefined %}
+
+infixpat :: { LPat GhcPs }
+infixpat : infixexp     {% (checkPattern <=< runPV) (unECP $1) }
 
 -- 'pats1' does the same thing as 'pat', but returns it as a singleton
 -- list so that it can be used with a parameterized production rule
```

(obviously I didn't implement the parsing actions.)

This goes without conflict through happy.

It is however a bit unclear whether we wan't that kind of flexibility.
Consider

```
instance Num (IO a) where
  fromInteger _ = pure undefined

foo :: IO a
foo = undefined

main = do
  1; 2 <- foo
  return 12
```

This type-checks today, and it interprets `1;2 <- foo` as two separate statements of the `do` block, meaning we can't interpret the LHS of `<-` as an Or pattern.
Users who *expect* to be able to write Or patterns without parens might be very confused by this.

Sigh. Sounds like another vote. 

On the other hand, @knothed and I can report that the layout rule in

```
f x = case x of
  (1
  2 -> 3
  (3; 5) -> 4
```
works out of the box even with parens (for the better or the worse).

**Comment by Ericson2314** [comment]
I like `|` because I think we can find a new syntax for guards instead.

**Comment by harpocrates** [comment]
> I like `|` because I think we can find a new syntax for guards instead.

I think `if` instead of `|` might work and it would read pretty nicely. OTOH, repurposing widely used syntax (even with a couple release cycles), seems like a bad idea as far as breakage to packages, tutorials, and papers.

**Comment by mixphix** [comment]
`'` isn't used for anything related and it's kind of the only other symbol that's easily accessible on most keyboards. Yeah it might look a bit out of place, until you start seeing it used...

**Comment by numlit2** [comment]
> `'` isn't used for anything related and it's kind of the only other symbol that's easily accessible on most keyboards. Yeah it might look a bit out of place, until you start seeing it used...

I like it. It's less noisy and less ugly than `;`.

**Comment by nfrisby** [comment]
I voted 🚀 because it seems unwise to me to try to give semicolon any meaning beyond layout.

I would have voted for pipe, at first thought, since it's well established for this, especially in other languages. But the idea of guards within sub patterns seems very natural to me. I wouldn't want to doom that possibility.

If breaking changes were magically harmless, I would vote for changing guard syntax to free up pipe for this. But that ship has sailed, I figure.

(Also, just for the record/context, I would have voted for prefix if I had been paying attention back when that vote was held. My apologies.)

I also think apostrophe will be confusing. Seems like a total non sequitur to me 🤷

I personally think ∨ would be a good choice. I wouldn't want \/ for this, but also wouldn't object to that if it's completely mandatory to have an ASCII equivalents. A need for Or-patterns has come up so rarely in my experience that I don't think it needs to be trivial to type this on a keyboard. (Sounds like famous last words of course… we could always add \/ later if my conjecture is disproven.)

**Comment by googleson78** [comment]
> I voted :rocket: because it seems unwise to me to try to give semicolon any meaning beyond layout.

Having a prefix layout herald for or patterns easily solves this issue as well, because in that scenario `;`s do retain their traditional meaning of "use this instead of newlines in layout". But alas.

**Comment by mixphix** [comment]
I can't help but interpret your reasoning as anything but an argument *against* using semicolons. We would then have the legal syntax `case a of A; B -> r1; C -> r2` which is incredibly confusing?

**Comment by nomeata** [comment]
It's probably confusing because it's unfamiliar (like any syntax). Mentally replace `;` with `|` and it looks absolutely natural to any Ocaml programmer…

**Comment by mixphix** [comment]
It serves two distinct purposes in the same line. If the lexer can handle it without proper bracketing, then I guess it's fine, but it still seems like a bad design decision to me. Sure, most Haskell uses layout instead of semicolons anyway, but if you're asking me to replace it with another character for it to make sense...

**Comment by cartazio** [comment]
i like the `\/` that was mentioned earlier, its not really used in existing haskell code, so theres no "whats this syntax mean in this context".

**Comment by klapaucius** [comment]
> It serves two distinct purposes in the same line.

no it's not. the purpose is always the same. ocaml just has at least three different line-of-code delimiters for bizarre historic reasons. you don't have to make the same mistakes.

**Comment by doyougnu** [comment]
I voted :heart: for the reasons stated above. We already have a kind of symbol to mean `match the rest` and that is `_`, so this seems to me to be a way to qualify that match and make `_` less permissive. But of course I cannot think of any appealing combination using `_`.

**Comment by leonschoorl** [comment]
> Compared to `(p1;p2)`: No risk of confusion with record field matches `(T1{x=_;y=_}; T2{})`

Maybe i'm misunderstanding or missing something, but aren't record fields supposed be separated by commas (`,`) ?

**Comment by hsenag** [comment]
is `||` out of the question?

**Comment by sgraf812** [comment]
This is a very tough choice, unfortunately. 
Currently, `;` leads by just one vote; it used to be the case that `|` led by about 3 votes (it also used to be the other way around).

I will leave this vote open for a good 24h until Monday AOE (which is Tues 12 GMT) and then will declare a winner that will be proposed to the committee.

**Comment by j-mie6** [comment]
> It's probably confusing because it's unfamiliar (like any syntax). Mentally replace `;` with `|` and it looks absolutely natural to any Ocaml programmer…

And Scala programmer!

**Comment by dixonary** [comment]
Definitely a 🎉 from me.

Semicolon `;` is used for sequencing in nigh every language, including Haskell. I think using it for this syntax would be quite unfortunate, and confusing to newcomers - something which (I hope) we are trying to reduce incidence of these days.

`|` is quite overloaded in Haskell, but it does already have the meaning of sum, as in data declarations, so using it the same way here makes sense. The fact that guards already use it is unfortunate but, IMO, less semantically confusing than `;`, even when `|` appears in closer proximity. 

On @simonpj 's point:

> I don't expect or-patterns to be common [...]

Even if the use of OR patterns were rare--actually I think it does come up quite often, especially in well-typed business logic--the mixture of OR patterns and guards in the same match would definitely be rarer, so the particular case you bring up of the mixture being unlovely isn't so critical.

For now I also use let-bindings to solve the problem but it's far less clean.

**Comment by L0neGamer** [comment]
@dixonary I would agree that `;` is used for sequencing; hence why it's used here, in syntax that tries each pattern in order from left to right. Personally I feel that using | in patterns will result in confusion with guards, as others have outlined.

**Comment by hsenag** [comment]
> I will leave this vote open for a good 24h until Monday AOE (which is Tues 12 GMT) and then will declare a winner that will be proposed to the committee.

I'd suggest that the summary for the committee is that there's roughly balanced support for the two options, and no clear winner.

**Comment by nomeata** [comment]
We can just have two extensions `SemicolonOrPatterns` and `BarOrPatterns` and everyone can have the Haskell they prefer!

**Comment by sgraf812** [comment]
> This is a very tough choice, unfortunately. Currently, `;` leads by just one vote; it used to be the case that `|` led by about 3 votes (it also used to be the other way around).
> 
> I will leave this vote open for a good 24h until Monday AOE (which is Tues 12 GMT) and then will declare a winner that will be proposed to the committee.

Alright, closing the vote now. 

The winner is `(p1; p2)` with 48 votes, followed by `(p1 | p2)` with 43 votes, followed by any other operator with 12 votes.

I want to thank everyone who contributed to the discussion! We'll formulate the amendment proposal in terms of `(p1; p2)` (simply because we think that the committee can only act on a concrete instance) and let the committee know that the alternative `(p1 | p2)` was received just as well as `p1; p2`.

**Comment by bradrn** [comment]
> We'll formulate the amendment proposal in terms of `(p1; p2)`

In that case, may I request that you also let the committee know about the option to use the layout rule? Personally, that was a big reason why I voted for the semicolon.

**Comment by knothed** [comment]
The votes have been settled, and the proposal is out: #609.

Thank you all for your participation in the votes and for your many suggestions!
