### ISSUE TITLE
Deriving Template Haskell

### ISSUE THREAD

**Issue by BurningWitness** [ghc-proposals/ghc-proposals#614]
Surprisingly I can't find any discussions on this, though it heavily relates to [#9813](https://gitlab.haskell.org/ghc/ghc/-/issues/9813).

### Motivation

Convergence of several problems:

- Basic deriving is a black box, if it doesn't work you can't extend it;

- Generic deriving was introduced as a solution to the previous point, but it's awkward to write, relies heavily on GHC optimizations and consequently slows down compilation;

- Template Haskell is fast, but requires splitting the code into declaration groups.

As such a lot of the Template Haskell usage is just for writing fast deriving instances, something that logically shouldn't require the inconvenience of declaration group splitting.

### Proposed change

A `DeriveTemplateHaskell` extension, allowing the following deriving form:

```haskell
deriving (thFun :: (DataD | NewtypeD | DataInstD | NewtypeInstD) -> Q [InstanceD])
```

where the datatype declaration is that for which the instance is being derived.

Additionally `DerivingStrategies` would get a new `template` strategy.

---

My assumption here is that the narrowing down of the type environment scope in GHC 7.8 was due to problems in mutual datatype declarations and the proposed definitions can only create instances. As such it would seem no big changes are required to make this work.

**Comment by int-index** [comment]
> As such a lot of the Template Haskell usage is just for writing fast deriving instances, something that logically shouldn't require the inconvenience of declaration group splitting.

If you wish to avoid declaration group splitting, presumably the instance head should be known _before_ TH is run, so that the constraint solver could resolve instances without running the TH code. But this isn't so in the proposed syntax:
```
deriving (thFun :: (DataD | NewtypeD | DataInstD | NewtypeInstD) -> Q [InstanceD])
```

What is the head of `InstanceD`? Impossible to know before `thFun` is run. So here's an alternative idea: make the `template` strategy a variant of `via`

```
deriving Monoid via template thFun
  -- thFun :: DataD -> Q [Dec]
```

**Comment by treeowl** [comment]
The next challenge: associated type and data families.

**Comment by BurningWitness** [comment]
@int-index

> What is the head of InstanceD?

Valid point, however one of the (in my mind) valid sidecases is lens deriving and that produces multiple instances per one function. Semantically I agree, something like `deriving Foo via template thFun` is much more pleasant to the ear, but it also implies a very specific instance.

> presumably the instance head should be known before TH is run

My naive assumption is that in this specific case `thFun` can be run together with the other deriving clauses. If I write `deriving (Eq, Eq)`, the duplicate instances are reported as defined on different lines, so I think of deriving clauses as merely code generation.

**Comment by BurningWitness** [comment]
@treeowl Deriving only works on datatype declarations, so out of those only data instances apply, unless I'm missing something.

**Comment by BurningWitness** [comment]
While this feature is a plausible one, my opinion on lens and records in general has changed quite a bit since when I made this issue. I no longer consider this a worthwhile addition.
