### ISSUE TITLE
Agda had `BlockArguments` first!

### ISSUE THREAD

**Issue by andreasabel** [ghc-proposals/ghc-proposals#622]
https://github.com/ghc-proposals/ghc-proposals/blob/740cf824a949822997182f34dd1ed4ad15bea46c/proposals/0000-ghc2024.rst?plain=1#L353
Don't forget Agda!  We were the first!

**Comment by nomeata** [comment]
TIL, thanks! Just use the suggested edit feature at #613 to improve the proposal text. Feel free to add more pros and cons if you think the text there is insufficient.

**Comment by andreasabel** [comment]
Mmh, the `Edit file` option is greyed out in this PR...

**Comment by nomeata** [comment]
Yeah, github is unhelpful, you’d have to navigate to the source branch yourself. Added the reference.
