### ISSUE TITLE
Breaking Change: Should guards open a layout block?

### ISSUE THREAD

**Issue by sgraf812** [ghc-proposals/ghc-proposals#679]
Motivated by https://gitlab.haskell.org/ghc/ghc/-/issues/25322, I'm in the process of writing a custom layouter that does not need to call out to the parser to find syntax errors. I'm making good progress so far, however there is at least one case which I cannot find a parser-less solution for. Take this code [inspired by `bytestring`](https://github.com/haskell/bytestring/blob/c967aca1fcc0300f8cc62071533fadb429814763/Data/ByteString/Lazy.hs#L547-L551):

```hs
foo :: Int -> Int
foo a     | even a = case sum [0..a] of
  42 -> 1
  _  -> 2
          | otherwise = 3
```

The "expected" laid out result is

```hs
foo :: Int -> Int
foo a     | even a = case sum [0..a] of
  {42 -> 1
  ;_  -> 2
          }| otherwise = 3
```

I'm having a hard time seeing how a layouter that works independently of the grammar could insert the closing curly brace before `|`.

Furthermore, consider this slightly evolved program, in which I do a guarded case split in the wild card alternative:

```hs
foo a     | even a = case sum [0..a] of
  42 -> 1
  x  | even x    -> 2
     | otherwise -> 3
          | otherwise = 4
```

This program is currently rejected by the parser, pointing out a parse error at `=`. Presumably it is laid out like this (although the final curly is never produced because the program is rejected):

```hs
foo a     | even a = case sum [0..a] of
  {42 -> 1
  ;x  | even x    -> 2
      | otherwise -> 3
          | otherwise = 4}
```

This seems *very* counterintuitive, because I just took a parsing program and made supposedly local, compositional changes that should not affect whether I get a parser error in a completely different position. 

I would go as far as saying that this is just unintended behavior in the current specification of layout.
I would prefer to reject both programs (a breaking change), if only in order to simplify the layout mechanism.

# Pre-Proposal

I would suggest that guards take part in layout, in the same way that guards in MultiWayIf do. When MultiWayIf is laid out, no semicolons are generated. In essense, we simply use `|` as column indicators. In this world, the original `foo` would lay out as

```hs
foo :: Int -> Int
foo a     {| even a = case sum [0..a] of {}
  }42 -> 1
  _  -> 2
          | otherwise = 3
```

Which immediately yields a parse error. Note that the `of` block is immediately closed because `42` is on an indentation level that is *below* that of the enclosing layout block pertaining to the guard `| even a`.
(Incidentally, this is the same behavior as if one had desugared the guard into a `case` or MultiWayIf.)

Of course, the second program will be rejected as well. One could rewrite the program as

```hs
foo a | even a = case sum [0..a] of
          42 -> 1
          _  -> 2
      | otherwise = 3
```

which lays out as

```hs
foo a {| even a = case sum [0..a] of
          {42 -> 1
          ;_  -> 2
      }| otherwise = 3}
```

---

What do you think?

**Comment by Ericson2314** [comment]
https://github.com/haskell/happy/issues/235 Did you consider this thing by any chance? I would be happy either with resolving layout actually during lexing (as you propose), or actually during parsing (as the paper does) over the status quo of bastardized-interleaved lexing/parsing implementing layout.

**Comment by maralorn** [comment]
I think this is a really tricky change in regard to stability. As far as I can tell, we only can really reap the primary intended benefit (i.e. simplifying the lexer parser interplay) from this change if we completely remove the old behavior from GHC. This means that guarding this behind a language extension (lets say NoUnindentedGuardLayout) would basically make this project moot.
I fear that before the committee could consider such a breaking change we would need to have some kind of empirical impact assessment (as often happens for breaking CLC proposals).

**Comment by Ericson2314** [comment]
I think we should be able to switch parsers based on language extensions. We can parse language extension programs from lexer without layout and very simple parser.

**Comment by sgraf812** [comment]
> https://github.com/haskell/happy/issues/235 Did you consider this thing by any chance?

No, I didn't. My goal was to have a layout pass that is separate from the parser.

> I think this is a really tricky change in regard to stability.

Indeed, this is a breaking change. But it is a breaking change that is easily fixed by an automated tool; it should be reasonable to detect such program fragments such as in the OP and rewrite it to

```hs
foo :: Int -> Int
foo a     | even a = case sum [0..a] of
  {42 -> 1
  ;_  -> 2}
          | otherwise = 3
```

which is a program that is accepted even after the breaking change.

Introducing a language extension to guard this behavior is a bit beside the point, because the intention was to make GHC simpler and produce better error messages.

---

However, meanwhile I have found that a parser-less layouter would incur even more breaking changes, see [this comment](https://gitlab.haskell.org/ghc/ghc/-/issues/25322#note_589630). It still possible to write a migration tool so these breaking changes aren't too tragic, but it renders the whole parser-less layouter idea far less tractable. 

Given that realisation, I don't think the breaking change in the OP is worth having, unless there is further motivation. I'll close this issue.

**Comment by maralorn** [comment]
Just for future reference, automatic migration tools are nice, but they don’t help you that much if the problem affects a dependency for which you can’t make new releases. We would also need to make sure that the problem is fixed in all "actively used" libraries in the ecosystem in the moment of release.

Also this particular topic has funny interactions with code formatters. (i.e. in theory a CI could reject the fix, although I’d hope common formatters wouldn’t even emit the problematic code in the first place.)
